# 서버 포트 설정
server:
  port: 80


#  spring 설정
spring:
  # DB 드라이버 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/jpaPrac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8236

  # 파일 업로드를 위한 설정
  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Documents\ReviewProjectData
      max-request-size: 30MB
      max-file-size: 10MB
  
  # JPA 설정
  jpa:
    hibernate:
      # SQL 을 자동으로 DB에 반영
      ddl-auto: update
    properties:
      hibernate:
        # hibernate query format에 맞추는 설정
        format_sql: true
        #hibernate query 를 출력하는 설정
        show_sql: true
  
  # template engine - thymeleaf 설정
  thymeleaf:
    # view 의 캐싱 설정
    cache: false

  # 로그 설정
logging:
  level:
    # sql ? 가 드어가는 부분을 추적하는 설정
    org.hibernate.type.descriptor.sql: trace

  # 변수 설정
com:
  adamsoft:
    upload:
      path: C:\Users\user\Documents\ReviewProjectData