server:
  port: 80

# DB ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpaPrac
    username: root
    password: 8236

  # JPA ??
  # Entity ? ??? ???? ?? ??? ??? ????.
  # ddl auto : ~
  # create      :?? ? ? ??? ?? ??
  # create-drop : ??? ? ???? ??? ? ??
  # update      : ???? ??
  # validate    : ??? ??
  # none        : ???? ???.
  jpa:
    hibernate:
      ddl-auto: update # hibernate? ddl ? ???? ????  DB? update

    # sql format ? ??? ???? sql ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# ?? ?? ??? ? ? ? ?? ??
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
