# 서버 포트 설정
server:
  port: 80


#  spring 설정
spring:
  # OAuth 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 38f43ff5aee9ea89cc35c4503953906c
            client-secret: EnGcSiLEKbQlwNn9x11BxXZzlsEspMDq
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
           authorization-uri: https://kauth.kakao.com/oauth/authorize
           token-uri: https://kauth.kakao.com/oauth/token
           user-info-uri: https://kapi.kakao.com/v2/user/me
           user-name-attribute: id

  # DB 드라이버 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/jpaPrac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8236

  # 파일 업로드를 위한 설정
  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Documents\ReviewProjectData
      max-request-size: 30MB
      max-file-size: 10MB
  
  # JPA 설정
  jpa:
    hibernate:
      # SQL 을 자동으로 DB에 반영
      ddl-auto: update
    properties:
      hibernate:
        # hibernate query format에 맞추는 설정
        format_sql: true
        #hibernate query 를 출력하는 설정
        show_sql: true
  
  # template engine - thymeleaf 설정
  thymeleaf:
    # view 의 캐싱 설정
    cache: false

  # 로그 설정
logging:
  level:
    # sql ? 가 드어가는 부분을 추적하는 설정
    org.hibernate.type.descriptor.sql: trace

  # 변수 설정
com:
  adamsoft:
    upload:
      path: C:\Users\user\Documents\ReviewProjectData